fgci-org/fgci-ansible

compute.yml, local.yml, login.yml
All the roles are disabled by default so that sites who don't need them aren't affected.
=> Enable autofs, adauth, pam, lustre_client roles

tools/reinstall_computes.yml, tools/reinstall_node.yml
I stumbled upon this when wondering about why reinstallation fails, which turned out to be due to selinux, but anyway this is a minor improvement.
=> Use ansible file for touching rather than an external command

compute.yml, local.yml, login.yml
The autofs configuration needs to be done at the same time as the nfs mount configuration, as it's an alternative to the static mounts.
As it is, installation fails because NFS is needed for slurm and sshd host keys.
=> Move autofs role below nfs_mount role

compute.yml, install.yml, local.yml, requirements.yml
Autofs has to be run before ssh-keys/slurm/lustre/adauth. Also updated the version for ansible-role-lustre_client. There the mount dir permissions have been updated.
=> Changed role order for autofs.

examples/group_vars/all/all.example, roles/dns/defaults/main.yml, roles/dns/templates/resolv.conf.j2
Setting it to the cluster internal domain can be useful, so that short
name lookups first search the cluster internal domain.
Also modifies the example configuration to set the dns_resolv_search
and dhcp_common_domain variables.
=> Allow setting the DNS resolver search domain

requirements.yml
Fixed some bugs from ansible-role-adauth. Please add this latest version to upstream-devel.
=> Updated ansible-role-adauth

compute.yml, install.yml, local.yml, nfs.yml, requirements.yml
Added idmapd role to compute nodes. Disabled by default. Allows nfsv4 if domain not default dns domain. Also added samba role, that can be used if needed. Not necessary for compute nodes but some sites may benefit from this on e.g. nfs-node.
=> Added idmapd role

tools/pullReqs.sh
Otherwise ansible-pull-script might pull old versions and the
configuration becomes inconsistent.
=> Sync requirements to the install node after pulling

examples/group_vars/compute/compute.example, examples/group_vars/grid/grid.example, examples/group_vars/install/install.example, examples/group_vars/login/login.example, tests/test.yml
We can remove slurm_type from the example group_vars as well.
=> Remove slurm_type

ansible.cfg
By making the ansible_managed string not contain timestamps, usernames
etc. we can avoid ansible considering a file changed and triggering
service restarts needlessly.
See https://github.com/ansible/ansible/issues/5317
=> Set ansible_managed string in ansible.cfg

compute.yml, examples/group_vars/all/all.example, local.yml
Compute nodes run postfix too, so we should configure it. Also set
postfix_mydomain
(https://github.com/CSC-IT-Center-for-Science/ansible-role-postfix/pull/2)
in all.example.
=> Configure postfix on compute nodes

ansible.cfg, meta/main.yml
From http://docs.ansible.com/ansible/playbooks_error_handling.html#handlers-and-failure
: 
"When a task fails on a host, handlers which were previously notified will not be run on that host. This can lead to cases where an unrelated failure can leave a host in an unexpected state. For example, a task could update a configuration file and notify a handler to restart some service. If a task later on in the same play fails, the service will not be restarted despite the configuration change."
=> Force handlers and set ansible_min_version to 2.0

ansible.cfg
Question: do we want to enable callback plugin by default?
- prints the time it takes for each task as well as a summary at the end
- the output is cluttered after this change and one can't change it much, one can increase the number of tasks shown at the end with environment variable PROFILE_TASKS_TASK_OUTPUT_LIMIT [1]
- seeing as many updates to ansible lately are about improving the performance this could be useful.
[1]: https://github.com/ansible/ansible/blob/7f8e8ddca9cf103c05bf39d68ebb2e2ded4067f2/lib/ansible/plugins/callback/profile_tasks.py
<pre>
$ ansible-playbook compute.yml -t cuda -D -l gpu
PLAY [grab facts from install nodes] *******************************************
skipping: no hosts matched
PLAY [Compute Nodes] *********************************************************** …
=> enable profile_task callback plugin by default

compute.yml, grid.yml, login.yml, nfs.yml, requirements.yml
This role populates /etc/hosts on the nodes based on the int_ip_addr and ib_ip_addr host variables. Should help https://github.com/CSC-IT-Center-for-Science/fgci-ansible/issues/129.
I'll add the role to local.yml in a follow-up commit, in case you want to wait a while for sites to catch up.
=> Add hosts-int role

examples/group_vars/admin/admin.example, examples/group_vars/grid/grid.example, examples/group_vars/install/install.example, examples/group_vars/login/login.example, roles/network_interface/defaults/main.yml, roles/network_interface/tasks/main.yml
Set the default network scheduler to "fq". On routers (NAT gateways)
it's recommended to override this and set
network_scheduler="fq_codel".
=> Set default network scheduler to fight bufferbloat.

admin.yml, compute.yml, grid.yml, install.yml, local.yml, login.yml, nfs.yml, roles/systemd_rpcbind/README.md, roles/systemd_rpcbind/defaults/main.yml, roles/systemd_rpcbind/tasks/main.yml, roles/systemd_rpcbind/templates/systemd_override_rpcbind.socket.j2, tests/test.yml
The bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1411412
tldr; rpcbind.socket from rpcbind -38 from EL has some changes which makes dbus unhappy on our clusters. This role reverts that change.
- new role systemd_rpcbind which is not in requirements.yml but directly in fgci-ansible (because it's a Temporary Workaround [1] and https://github.com/CSC-IT-Center-for-Science/fgci-ansible/commit/edd931409bd708d4bfd17d099498467c241d33d5
- added to all playbooks https://github.com/CSC-IT-Center-for-Science/fgci-ansible/commit/cfb1015552572c6d91ff5cd2eb4d0145a6b05c0a
- added to testing https://github.com/CSC-IT-Center-for-Science/fgci-ansible/commit/c9c61d46fcd9b97d585f99ccd92c0fb35c308167
[1]: http://devhumor.com/content/uploads/images/April2016/temporary.jpg
=> Override systemd rpcbind.socket

examples/group_vars/all/fgci-default-packages, examples/group_vars/compute/compute.example, examples/group_vars/compute/fgci-default-packages, examples/group_vars/login/login.example, examples/group_vars/nfs/nfs.example
Since FGCI is using Lmod, make sure that the old Tcl environment
modules package is not installed, in order to avoid potential
confusion.
=> Remove old Tcl environment modules package

.travis.yml, tests/test.yml
This means that travis jobs should now be nice and green in github, but we still test the poorly labeled test "latest-epel-centos7" (which tries to run fgci-ansible playbooks with master of all the roles in requirements.yml - and there are some issues when doing that causing it currently to fail).
Bonus fix: make the sshd role work in docker too. The ansible template module to configure sshd in that role has a validation. And that validation command fails because for some reason there are no sshd host keys generated at that stage. I assume this is a docker issue, but. 
I didn't check if this is an issue for real hardware.
=> Test allow failure

examples/group_vars/compute/compute.example, examples/group_vars/login/login.example, examples/group_vars/nfs/nfs.example
For UEFI boot one needs a /boot/efi partition formatted as FAT. Make
sure such a partition is always created. For BIOS boot it makes no
difference.
=> Kickstart partitioning that works for UEFI too

examples/group_vars/compute/compute.example
As of CentOS 7.4 ansible was moved from the EPEL repo to the CentOS
extras repo. For some reason it doesn't work to add centos extras to
the repo list in kickstart, hence ansible must be installed separately
in the kickstart %post section. It must also be removed from the list
of packages to install in kickstart, which is what this patch does.
=> Remove ansible from compute kickstart_packages

roles/network_interface/tasks/main.yml
The | changed way of doing things is deprecated in Ansible 2.5, change it to "is changed" as it should be.
=> |changed is getting deprecated

tests/devel-centos7/Dockerfile
Before this PR we were seeing errors from PyOpenSSL when pip installing anything with pip 10.0 inside CentOS7 docker container
=> Fix testing with pip - (don't pip install requests[security] )

ansible.cfg
Fixes this:
<pre>
TASK [ansible-role-fgci-install : synchronize group_vars/ to
/var/www/html/group_vars/ - for ansible-pull - secrets and firewalls are
not needed] ****************************
Thursday 31 May 2018  14:32:53 +0300 (0:00:00.218)       0:00:10.967
**********
fatal: [myserver.example.com]: UNREACHABLE! => {"changed": false,
"msg": "Authentication or permission failure. In some cases, you may
have been able to authenticate and did not have permissions on the
target directory. Consider changing the remote tmp path in ansible.cfg
to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p
\"` echo /root/.ansible/tmp/ansible-tmp-1527766374.13-139832550625802
`\" && echo ansible-tmp-1527766374.13-139832550625802=\"` echo …
=> Change remote_tmp to /tmp/.ansible

ansible.cfg
As of ansible 2.2, the default value of scp_if_ssh is the new 'smart'
option, meaning it will try both sftp and scp.  In any case, there was
never any particular need to choose a non-default value here.  Thus,
lets just use the default.
=> Remove scp_if_ssh from ansible config

roles/network_interface/tasks/main.yml
This is useful when working with images as opposed to live hosts.
=> Don't set sysctl when target is a chroot

requirements.yml
Updated:
- Make role work for chroot images
- Fix depreciation warning wrt yum/with_items
- Optionally setup IB partitions for chroot images
- Add .gitignore
=> Bump Lustre role

requirements.yml
Main change is to use pdsh packages from OpenHPC, but other than that
should be no user-visible changes.
=> Update ansible-role-pdsh-genders to v1.3.1

roles/network_interface/templates/infiniband_RedHat.j2
When using Lustre LNet multi-rail it's still useful to split different
server adapters into separate subnets, but no need to create multiple
pseudo devices on the clients, it suffices to just have multiple IP's
on the same interface.
=> Allow multiple IP's per interface for IB

requirements.yml
New version enables use of network device aliases for multi-rail.
=> Bump ansible-role-lustre-client version

roles/dns/handlers/main.yml, roles/dns/tasks/main.yml, roles/dns/tasks/redhat.yml, roles/network_interface/tasks/main.yml, roles/network_interface/vars/CentOS-8.yml
In case we need to use Network Manager in the future, making sure we already take this into account. Only included in Centos 8 and newer systems.
=> Making code more robust wrt Network Manager

requirements.yml
Improves compatibility with RHEL/CentOS 8
=> Update ansible-sshd to v0.8.3
